language: rust
os:
    - linux
    - osx
env:
  global:
    - secure: kd+Q+IWrHUZK+BwwEh37IiR7B76yyvfjAB3Gx6roshKyAk2KmduoyLGv6v902gbLAtt/8JtPMBHZdKbMv7A1eKBsCOF/rMz1rHziuTbnFwfnx6UN+jalZZRIYmn20M7I1UfvhcvWXqvcrpo84NbhOYlXMmvI+X6HZ2rSIsYta6E=
    - VERBOSE: 1
script:
    - sudo sed -i 's/secure_path="/secure_path="\/home\/travis\/rust\/bin:/' /etc/sudoers
    - sudo -E LD_LIBRARY_PATH=$LD_LIBRARY_PATH sh -c "make && make test && make doc"
after_script:
    - cd target
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sudo sh
notifications:
    irc:
        channels:
            - "chat.freenode.net#libpnet"
        use_notice: true
