language: rust
os:
    - linux
    - osx
before_script:
    - rustc -v
    - cargo -V
env:
  global:
    - secure: UMDMDJdHlaLSQou1vZpfhkKpXFEtb10IdSrL1LWuEICXnQNR977ld8WSkmHM2P8hc6pRlqe42q/LIQ0Zf6iBddc91b/WLHezwfZAieUjB/eh3R0Jd9C2ReVxA+jGSZCojehnZG3f278+bQPUyyIkb0ofK5SmwDE0GoxRWoeChsw=
    - VERBOSE: 1
script:
    - sudo sed -i 's/secure_path="/secure_path="\/home\/travis\/rust\/bin:/' /etc/sudoers
    - sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH sh -c "make && make test && make doc"
after_script:
  - cd target
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sudo sh
