environment:
  RUST_TEST_THREADS: 1
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      RUST_CHANNEL: 1.15.0
      WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/x64/Packet.lib"
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"
    - TARGET: i686-pc-windows-msvc
      RUST_CHANNEL: 1.15.0
      WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/Packet.lib"
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\vcvars32.bat"
    - TARGET: x86_64-pc-windows-msvc
      RUST_CHANNEL: stable
      WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/x64/Packet.lib"
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"
    - TARGET: i686-pc-windows-msvc
      RUST_CHANNEL: stable
      WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/Packet.lib"
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\vcvars32.bat"
    - TARGET: x86_64-pc-windows-msvc
      RUST_CHANNEL: beta
      WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/x64/Packet.lib"
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"
    - TARGET: i686-pc-windows-msvc
      RUST_CHANNEL: beta
      WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/Packet.lib"
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\vcvars32.bat"
    - TARGET: x86_64-pc-windows-msvc
      RUST_CHANNEL: nightly
      WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/x64/Packet.lib"
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"
    - TARGET: i686-pc-windows-msvc
      RUST_CHANNEL: nightly
      WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/Packet.lib"
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\vcvars32.bat"
install:
  # Install Rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_CHANNEL%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  # Install dependencies
  - ps: mkdir C:/dl
  - curl -o "C:/dl/wpd.zip" "https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip"
  - ps: Add-Type -AssemblyName system.io.compression.filesystem
  - ps: "[io.compression.zipfile]::ExtractToDirectory(\"C:/dl/wpd.zip\", \"C:/dl/wpdpack\")"
  - ps: mkdir ${env:APPVEYOR_BUILD_FOLDER}/lib
  - ps: cp ${env:WPD_LIB_PATH} ${env:APPVEYOR_BUILD_FOLDER}/lib
  - CALL "%VCVARS%"
  - choco install winpcap
  # Print versions, for diagnostics
  - rustc -V
  - cargo -V
build: false
test_script:
    - cargo test --verbose --features appveyor

skip_branch_with_pr: true
