[package]

name = "pnet"
version = "0.0.1"
authors = [ "Robert Clipsham <robert@octarineparrot.com>" ]
license = "MIT/Apache-2.0"
homepage = "https://github.com/libpnet/libpnet"
repository = "https://github.com/libpnet/libpnet"
documentation = "http://octarineparrot.com/assets/libpnet/doc/pnet/"
description = "Cross-platform, low level networking using the Rust programming language."
readme = "README.md"
keywords = ["network", "networking", "transport", "datalink", "packet", "protocol"]

[lib]

name = "pnet"
crate_type = [ "rlib", "dylib" ]
