[package]
name = "pnet"
version = "0.19.0"
authors = [ "Robert Clipsham <robert@octarineparrot.com>" ]
license = "MIT/Apache-2.0"
homepage = "https://github.com/libpnet/libpnet"
repository = "https://github.com/libpnet/libpnet"
description = "Cross-platform, low level networking using the Rust programming language."
readme = "README.md"
keywords = ["networking", "transport", "datalink", "packet", "protocol"]
categories = ["network-programming", "parser-implementations"]
build = "build.rs"

[features]
default = ["pnet_packet/with-syntex"]
benchmark = []
netmap = ["netmap_sys"]
appveyor = []
travis = []

[dependencies]
libc = "0.2"
ipnetwork = "0.12"

pnet_base = { path = "pnet_base" }
pnet_sys = { path = "pnet_sys" }
pnet_datalink = { path = "pnet_datalink" }
pnet_packet = { path = "pnet_packet" }

clippy = { version = ">=0.0", optional = true }
pcap = { version = "0.6", optional = true }
netmap_sys = { version = ">=0.0", optional = true, features = ["netmap_with_libs"] }

[dev-dependencies]
time = ">=0.1"
