[package]

name = "pnet"
version = "0.4.0"
authors = [ "Robert Clipsham <robert@octarineparrot.com>" ]
license = "MIT/Apache-2.0"
homepage = "https://github.com/libpnet/libpnet"
repository = "https://github.com/libpnet/libpnet"
documentation = "http://octarineparrot.com/assets/libpnet/doc/pnet/"
description = "Cross-platform, low level networking using the Rust programming language."
readme = "README.md"
keywords = ["networking", "transport", "datalink", "packet", "protocol"]

links = "packet"
build = "build.rs"

[lib]

name = "pnet"
crate_type = [ "rlib", "dylib" ]

[features]

default = ["clippy"]
netmap = ["netmap_sys"]
appveyor = []

[dependencies.clippy]
optional = true
version = ">=0.0"

[dependencies.netmap_sys]
features = ["netmap_with_libs"]
optional = true
version = ">=0.0"

[dependencies.pnet_macros]
path = "pnet_macros"
version = ">=0.3"

[dev-dependencies]
time = ">=0.1"
