[package]
name = "pnet_packet"
version = "0.19.0"
authors = ["Robert Clipsham <robert@octarineparrot.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/libpnet/libpnet"
repository = "https://github.com/libpnet/libpnet"
description = "Cross-platform, binary packet parsing and manipulation"
keywords = ["networking", "packet", "parsing", "raw"]
categories = ["network-programming", "parser-implementations"]
build = "build.rs"

[dependencies]
pnet_base = { path = "../pnet_base" }
pnet_macros_support = { path = "../pnet_macros_support", version = ">=0.1" }

[build-dependencies]
glob = "0.2"
syntex = { version = "0.42" }
pnet_macros = { path = "../pnet_macros", version = ">=0.13" }
